version: 2
jobs:
  build:
    docker:
#        - image: circleci/ruby:2.4.1-node-browsers
        - image: cvhbsk/ubuntu-custom        

    steps:
        - run: apt-get install libapr1-dev openjdk-8-jdk libssl-dev
        - checkout
        - run:
            name: Install fpm-cookery
            command: gem install fpm-cookery
        - run:
            name: Install build dependencies
            command: sudo fpm-cook install-deps
        - run:
            name: Build RPM
            command: fpm-cook