version: 2
jobs:
  build:
    docker:
#        - image: circleci/ruby:2.4.1-node-browsers
        - image: ubuntu        

    steps:
        - run: 
            name: Install required dependencies
            command: apt update && apt-get install git ruby libffi-dev -y
        - checkout
        - run:
            name: Install fpm-cookery
            command: gem install fpm-cookery
        - run:
            name: Install build dependencies
            command: sudo fpm-cook install-deps
        - run:
            name: Build RPM
            command: fpm-cook