version: 2
jobs:
  build:
    machine:
       - circleci/classic:latest

    steps:
        - run:
            command: ls
#      - checkout
#
#      - run:
#          name: install fpm-cookery
#          command: |
#            gem install fpm-cookery
#            sudo fdisk -l
#
#      # collect reports
#      - store_test_results:
#          path: /tmp/test-results
#      - store_artifacts:
#          path: /tmp/test-results
#          destination: test-results