version: 2
jobs:
  build:
    docker:
        - image: circleci/ruby:2.4.1-node-browsers

    steps:
        - checkout
        - run:
            name: Install fpm-cookery
            command: gem install fpm-cookery
        - run:
            name: Build RPM
            command: fpm-cook


#      - run:
#          name: install fpm-cookery
#          command: |
#            gem install fpm-cookery
#            sudo fdisk -l
#
#      # collect reports
#      - store_test_results:
#          path: /tmp/test-results
#      - store_artifacts:
#          path: /tmp/test-results
#          destination: test-results